language: ruby
cache: bundler

rvm:
  - 2.2
  - 2.1
  - 2.0
  - jruby

script: 'bundle exec rake'

notifications:
  email:
    recipients:
      - sebastian.schkudlara@vizzuality.com
    on_failure: change
    on_success: never

