language: ruby
cache: bundler

rvm:
  - 2.2
  - 2.1
  - 2.0
  - jruby

script: 'bundle exec rake'

env:
  - RAILS_VERSION="~>4.0.0"
  - RAILS_VERSION="~>4.1.0"
  - RAILS_VERSION="~>4.2.0"

notifications:
  email:
    recipients:
      - sebastian.schkudlara@vizzuality.com
    on_failure: change
    on_success: never

